### ISSUE TITLE
getBlockCount method error

### ISSUE THREAD

**Issue by mask-pp** [QuarkChain/pyquarkchain#361]
jsonrpc method getBlockCount can't show shard block height, and has no test case in test_jsonrpc.py .

**Comment by qizhou** [comment]
assign to @qcgg to triage

**Comment by qizhou** [comment]
Double checked the code.  There are two issues here:
1, getBlockCount shows the number of blocks mined by each miner.  It doesn't output the block height.  We should call getStats to obtain block height
2, ENABLE_TRANSACTION_HISTORY may be disabled so that getBlockCount won't return per-shard mining results.
