### ISSUE TITLE
使用过时组件pyCrypto

### ISSUE THREAD

**Issue by kakatototata** [QuarkChain/pyquarkchain#395]
## 使用过时组件
本项目中广泛使用了 `pyCrypto` 作为密码学算法库，该库已经停止维护，存在潜在的供应链安全问题。

**建议**：建议更换为 `pyca/cryptography` 实现。

**Comment by qizhou** [comment]
Again, please file different issues for better trackability.

**Comment by jyouyj** [comment]
I have checked our encryption library. I think we use cryptography in most cases. Only one place we find is p2p/auth.py, where we use the pycryptodome instead of pyCrypto. pycryptodome is an almost drop-in replacement for the old PyCrypto library. I think it is still maintaining. Could you give us some examples where pyCrypto is applied? @kakatototata

**Comment by kakatototata** [comment]
> I have checked our encryption library. I think we use cryptography in most cases. Only one place we find is p2p/auth.py, where we use the pycryptodome instead of pyCrypto. pycryptodome is an almost drop-in replacement for the old PyCrypto library. I think it is still maintaining. Could you give us some examples where pyCrypto is applied? @kakatototata

We mistakenly thought that the installed version is the pyCrypto library, which has stopped maintenance in 2014. The actual installation is pycryptodome 3.8.0, which is still being maintained and currently has no security issues.

**Comment by jyouyj** [comment]
Thank you for your response. If there are any problems with this issue, please let me know.
