### ISSUE TITLE
Unlimited P2P Conn Number Enables DoS Attack (with Mem Crash or Others)

### ISSUE THREAD

**Issue by xhyumiracle** [QuarkChain/pyquarkchain#400]
There's no restriction on the total number of connected peers, which enables the attacker to DoS arbitrary cluster by opening unlimited number of connections and exhausted its net resources, or to crash the server by occupying the memory resource. 

This vulnerability exists in both master/slave node, and will exist even after limit the size for each packet, like mentioned in #399, because attackers could send a small packet per peer but creating an enormous number of peers.

Like said in #399 , the cluster would shutdown after any subprocess crashed.

Suggestions were to put restrictions on the number of opening connections.

**Comment by qizhou** [comment]
master/slave is running in controlled env, so we are not worrying about opening conns among them.

The major concern is p2p peers.  Note that the p2p layer will restrict max number of conns, but it is possible to create connection even p2p doesn't discover it.  I would defer to @qcdll to confirm it.

In addition, it would be helpful to see how Bitcoin core and Ethereum address the issue.  Thanks.

**Comment by qcdll** [comment]
we do have limit on the number of peers for p2p connection
https://github.com/QuarkChain/pyquarkchain/blob/3f26e929f794cd722f2c736f1cab4aab7019e42c/quarkchain/cluster/cluster_config.py#L275
the p2p server will reject incoming handshake when max peer has reached, and will not proactively seek peer connections at certain number of connected peers. I don't think it is possible to sneak into peer connection because of how the server handles incoming connections. If you do discover any way to bypass the peer number limit, please let us know. Thanks

**Comment by qizhou** [comment]
To be clear, it is possible to connect a peer by just connecting it with IP without going through p2p layer?  If all connection must be established by p2p layer, then I think we could rely on p2p max_peers restrictions.

**Comment by qcdll** [comment]
I think all p2p connections must go through the port that p2p server is bound to, even if you already know IP/port/pubkey you still go through that port and subject to max_peer limitation

**Comment by qizhou** [comment]
Great explanation from @qcdll .  Please let us know if this addresses your concern and we could close the issue.  Thanks.

**Comment by xhyumiracle** [comment]
Thanks for reply.

Yes, DEFAULT_MAX_PEERS is 25, and yes, all peer connections must go through the handshake protocol. 

But what I concerned is that it is possible to open tcp connections on the server before establish a peer connection. We could open a tcp connection and write nothing into the stream, then the connection will stuck at the first 'read' function in _receive_handshake, which doesn't subject to the limit of peer number. Moreover, like I mentioned in #401 , these connections won't timeout, which makes it easier to slow or even crash the server by open too many active connections.

e.g, simple open 1000 connections hanging there for over 10 mins.
![image](https://user-images.githubusercontent.com/17793687/54574716-5fee9b00-4a2c-11e9-813e-c817ab3ca9f7.png)

**Comment by qcdll** [comment]
Got it, makes sense, I feel a reasonable read timeout (3s) should be able to handle this. Opening tcp connections should not consume too much resource on the host

**Comment by xhyumiracle** [comment]
BTW, Although this could be mitigated by fixing #401 , they're actually different issues. A possible fix for this one could be put a number restriction before the first read.

**Comment by xhyumiracle** [comment]
Just saw your reply. Yeah, the 3s timeout does ease this problem and maybe it's a good solution considering the performance.

**Comment by qizhou** [comment]
I am wondering how Ethereum and Bitcoin deal with it.  A simple way is that we will only one connection from one IP subnet.  This means an attacker must have 1000 IPs in 1000 subnets to perform the attack.

**Comment by qizhou** [comment]
In addition, a handshake timeout should be implemented, where geth uses 5 secs:

https://github.com/ethereum/go-ethereum/blob/358535188852bd9d8e351ccbb0d1fa608284a77b/p2p/rlpx.go#L65

**Comment by qcdll** [comment]
Reviewing the code does show that we already had handshake timeout implemented:
https://github.com/QuarkChain/pyquarkchain/blob/33e672242dea2b12745a9cbd26470d23ba18c11f/quarkchain/p2p/p2p_server.py#L188
https://github.com/QuarkChain/pyquarkchain/blob/33e672242dea2b12745a9cbd26470d23ba18c11f/quarkchain/p2p/p2p_server.py#L203

It seems to me that the "e.g, simple open 1000 connections hanging there for over 10 mins." symptom is caused by leaking fd (sockets left open when handshake failed) and had been fixed by https://github.com/QuarkChain/pyquarkchain/pull/397

@xhyumiracle please let us know of how we could reproduce "e.g, simple open 1000 connections hanging there for over 10 mins." so that we can verify

**Comment by xhyumiracle** [comment]
You're right, it is caused by socket leak and #397 did fix the p2p server. But as I mentioned #401 , if slaves are open to public, the threat might still exist.

**Comment by qcdll** [comment]
slaves are not open to public, also see #454

closing this one
