### ISSUE TITLE
__read_fully Won't Timeout

### ISSUE THREAD

**Issue by xhyumiracle** [QuarkChain/pyquarkchain#401]
*Connection* is the base class for most *\*Connection* classes. The function *__read_fully* is used by almost every connection. 

But it doesn't have a reasonable timeout, during receiving the first packet, it always wait to read all the n bytes data or an EOF. But if a client opens a connection and never close it, this connection would be open for a long time.

```python
    async def __read_fully(self, n, allow_eof=False):
        ba = bytearray()
        bs = await self.reader.read(n)
        if allow_eof and len(bs) == 0 and self.reader.at_eof():
            return None

        ba.extend(bs)
        while len(ba) < n:
            bs = await self.reader.read(n - len(ba))
            if len(bs) == 0 and self.reader.at_eof():
                raise RuntimeError("{}: read unexpected EOF".format(self.name))
            ba.extend(bs)
        return ba
```

This vulnerability could be used together with #400 and reduce the cost of a successful attack, increase the damage and risk.

Please check and fix it ASAP if confirmed. Thanks.

**Comment by qizhou** [comment]
I am not sure how Ethereum and Bitcoin core address the issue?  A simple way is to introduce timeout, but if there is a common practice, it will be much easier to adopt.

**Comment by qizhou** [comment]
go-ethereum also uses io.readFull

https://github.com/ethereum/go-ethereum/blob/358535188852bd9d8e351ccbb0d1fa608284a77b/p2p/rlpx.go#L666

to read per-frame (similar to the command to us).

**Comment by qizhou** [comment]
However, go-ethereum setup 30sec read timeout

https://github.com/ethereum/go-ethereum/blob/358535188852bd9d8e351ccbb0d1fa608284a77b/p2p/rlpx.go#L94

**Comment by qizhou** [comment]
We will add
- Timeout parameter for read()
- ping/pong in devp2p
- Timer to send ping/pong
- Handler for pong in devp2p

Basically, it is the same as go-ethereum implemntation.

**Comment by qcdll** [comment]
No, `__read_fully` is only used for internal RPC (intra-cluster communication between master and slave)

In p2p connections, `read_metadata_and_raw_data` (originally defined in `Connection`) which calls `__read_fully` is overriden:
https://github.com/QuarkChain/pyquarkchain/blob/33e672242dea2b12745a9cbd26470d23ba18c11f/quarkchain/p2p/p2p_manager.py#L286

... and it turns out we did not give it a timeout either. But does that really matter? a peer can be totally useless even if it sends us some rubbish packets periodically; or in the case of some ping/pong implementation, a malicious useless peer can adhere to ping/pong but remain useless.

Note that handshake timeout is already being handled/discussed in #400 

Also I will be closing this particular issue (unless there is any finding that `__read_fully` is actually used in p2p connections) and open a new one specifically for p2p read timeout and ping/pong

**Comment by xhyumiracle** [comment]
Agree, it is overriden in p2p connections with a reasonable timeout. 

When I was testing, I treat p2p and slave as the same since they all open to public by default.
Now that you close p2p rpc port, slave servers are still open to public by default and I guess it's by design? (no idea
https://github.com/QuarkChain/pyquarkchain/blob/master/quarkchain/cluster/slave.py#L918

And it uses __read_fully directly. So the same issue might exist on slave server.

**Comment by qizhou** [comment]
slave should only available internally.  We need to double check on this.

**Comment by qcdll** [comment]
slaves are not open to public
