### ISSUE TITLE
we should config slave to use localhost by default

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/pyquarkchain#454]
slave service is not designed to be public and its port to be private by default (similar to jsonrpc)

**Comment by qcdll** [comment]
the configuration of cluster is not known to the public, and host/port for slave server is not to be known by external parties

that said, any reasonably secure server on the Internet shall impose some firewall, which only allow traffic to certain whitelisted ports. we only need 2 ports for p2p UDP and TCP. I don't think binding slave to 0.0.0.0 poses more secure hazard

it may just need some documentation eg "running a private cluster" - "network security"

**Comment by qizhou** [comment]
Understood.  But from the social engineering perspective, I would imagine that a lot of users may not be aware of the slave servers that may be accessed externally by default. A social engineering attacker could quickly scan the nodes and figure out if their slave ports are open, and then perform the attack.

**Comment by qcdll** [comment]
ok, just make sure that we can successfully run a cluster out of the repo config.

i.e. any user who wish to join the consensus/mining shall be able to start a cluster without extensively adjusting the config file

**Comment by xhyumiracle** [comment]
> Understood. But from the social engineering perspective, I would imagine that a lot of users may not be aware of the slave servers that may be accessed externally by default. A social engineering attacker could quickly scan the nodes and figure out if their slave ports are open, and then perform the attack.

Agree, this is exactly what we wanted to suggest. From security principle prospective, we should never assume that users should take the responsibility to safely use the system with default config. Otherwise we could ignore all the XSS or SQL injection vulnerabilities in a CMS because we assume users should set up a WAF for there server.

Similar to what you concerned, we suggest that any user who launched the cluster with the default config should not expose any vulnerability. Users should take the risk only if they decide to modify the default config to start the slaves on different machines.

**Comment by xhyumiracle** [comment]
I apology if I was too annoying on illustrating this problem, just want to ensure that the system is complied with security concerns.

**Comment by ninjaahhh** [comment]
seems this is already finished? @jyouyj

**Comment by jyouyj** [comment]
Yes. The default port is set to 127.0.0.1.
