### ISSUE TITLE
区块时间检查不严格可能导致恶意挖矿

### ISSUE THREAD

**Issue by ohJohanZ** [QuarkChain/pyquarkchain#458]
root chain 只检查了当前块的create_time要大于prev块的时间，未限制可以超过多少，恶意矿工可以提交一个超前时间的区块，长时间阻止挖矿。

**Comment by qcdll** [comment]
I **don't** think we shall put limit on the time difference between current block vs prev.

Consider a scenario where the network partition caused some miners to go offline, or, in the event of unexpected difficulty adjustment (think difficulty bomb in eth, though I think it is flawed design), or even by the nature of POW, time between blocks is unbounded. Enforcing a max diff between blocks is unwise.

I think a better solution is to simply ignore blocks that are T seconds in the future. Currently our shard chains will not add/broadcast blocks that are 30seconds into the future, need to double check on the root chain.

Clock skew is going to cause issues if T is set too low. But I think it should be fine if T is on order of 10s of seconds

**Comment by ohJohanZ** [comment]
> I **don't** think we shall put limit on the time difference between current block vs prev.
> 
> Consider a scenario where the network partition caused some miners to go offline, or, in the event of unexpected difficulty adjustment (think difficulty bomb in eth, though I think it is flawed design), or even by the nature of POW, time between blocks is unbounded. Enforcing a max diff between blocks is unwise.
> 
> I think a better solution is to simply ignore blocks that are T seconds in the future. Currently our shard chains will not add/broadcast blocks that are 30seconds into the future, need to double check on the root chain.
> 
> Clock skew is going to cause issues if T is set too low. But I think it should be fine if T is on order of 10s of seconds

Yes, I mean that, you should compare create_time with node system time, but now you does not do any limit.

**Comment by qizhou** [comment]
Ethereum simply rejects any blocks with 15 sec greater create time.  I think we adopt it in shard blocks, but probably miss it in root blocks?

**Comment by qcdll** [comment]
go-ethereum does the following for blocks that bear a time in the future:
1. blocks that are >30sec into the future would not be added to queue for processing:
https://github.com/ethereum/go-ethereum/blob/22e1d2ce034a8674327e1cf6c01aff3fca403f71/core/blockchain.go#L1077-L1080
2. blocks that are >15sec into the future would not be considered valid blocks:
https://github.com/ethereum/go-ethereum/blob/0bec85f2e27d7b79f7700643cd9b38e74cecadfa/consensus/ethash/consensus.go#L236-L238

**Comment by qcdll** [comment]
did some research for **time**, and the proper way to keep it

what we are currently using as the "time" in block header is "unix time" (epoch) is properly defined as  *number of seconds that have elapsed since 00:00:00 Thursday, 1 January 1970, Coordinated Universal Time (UTC), minus leap seconds*. And because of the existence of leap seconds, the epoch actually JUMPS BACKWARD when a leap second occurs, see the example in the wikipedia article below.

Fortunately leap seconds do not occur often and are only +1s (for the moment). In the foreseeable future, unless days become too much longer, if we follow the same logic (allowing blocks a few seconds into the future) it should be fine

One lesson from this is that unix time is NOT a precise way of time-keeping, despite the fact that it should be enough for our purpose.

reference read:
https://en.wikipedia.org/wiki/Unix_time
https://en.wikipedia.org/wiki/Leap_second
https://docs.python.org/3/library/time.html#time.time *The specific date of the epoch and the handling of leap seconds is platform dependent.*
