### ISSUE TITLE
 txs without min gasprice

### ISSUE THREAD

**Issue by blackjliuyun** [QuarkChain/pyquarkchain#478]
Hi,there may be  a problem here that the txs without min gasprice. According to eth, if the node is mining, the default miner (policy) code will delete the tx from the tx pool after broadcast due to having too low gas price. The node will then accept the same tx again if it's re-sent by the attacker.
Furthermore, since txs are periodically deleted from the tx pool, it's possible that a node receives the tx again and cannot know that it has seen it before, thus causing a broadcast loop in the network
<img width="367" alt="image" src="https://user-images.githubusercontent.com/23147261/55942758-ae800580-5c77-11e9-8a1e-d3bfeb4d5693.png">

<img width="893" alt="image" src="https://user-images.githubusercontent.com/23147261/55942877-00289000-5c78-11e9-8a5c-6665fb018f0f.png">
https://github.com/ethereum/go-ethereum/issues/1320

**Comment by qcdll** [comment]
does quarkchain suffer from the same problem as in https://github.com/ethereum/go-ethereum/issues/1320 ? If I recall correctly, a tx with too low gas will fail to run

in your code screenshot, note the comment block `from_address will be set for execute_tx`, meaning that the actual transaction processing does not include this logic

**Comment by qcdll** [comment]
we currently allow 0 gas price transactions (on the other hand, transaction with 0 **startgas** will fail). and I think the linked issue ethereum/go-ethereum#1320 is specifically caused by NOT handling 0 gas price transactions.

But there is potentially an attack vector to create lots of transactions with 0 gas price and fill the miner transaction queue. But I think it is equally possible that the attacker can create lots of transaction with 1 gas price. So in the end I don't think this is a huge problem, just the miner transaction queue need to handle this case correctly.

**Comment by ninjaahhh** [comment]
https://etherscan.io/txs?a=0xf17f52151ebef6c7334fad080c5704d77216b732

**Comment by qizhou** [comment]
> https://etherscan.io/txs?a=0xf17f52151ebef6c7334fad080c5704d77216b732

I guess it is proposed by a miner?

**Comment by ninjaahhh** [comment]
> > https://etherscan.io/txs?a=0xf17f52151ebef6c7334fad080c5704d77216b732
> 
> I guess it is proposed by a miner?

seems it's related gas token https://gastoken.io/
