### ISSUE TITLE
Potential transaction re-broadcasting DDoS vulnerability 

### ISSUE THREAD

**Issue by ninjaahhh** [QuarkChain/pyquarkchain#551]
need more investigation before enabling transactions

for you to triage @qizhou

**Comment by ninjaahhh** [comment]
the current broadcast logic is 

0. clients call JSONRPC `sendTransaction` / `sendRawTransaction` endpoint
1. master try adding tx to the shard specified by the tx, exit if failed, otherwise
2. call `peer.send_transaction` to broadcast through P2P
3. peer shards (slaves handling the same shard) receive tx, try adding to local state, exit if failed, otherwise
4. broadcast to peers through P2P

the re-broadcasting will finish once nodes failed to add that tx to local state (either because already seen that tx, or already received the block containing that tx)

@qizhou do you see any potential problem in this flow?

**Comment by qizhou** [comment]
There is a chance the tx may be discarded if the tx queue is full.  In such case, we will also stop broadcasting the tx?

**Comment by ninjaahhh** [comment]
> There is a chance the tx may be discarded if the tx queue is full. In such case, we will also stop broadcasting the tx?

yes. tx queue full will result in failure for `add_tx`, thus will stop broadcasting at step 1 and 3

**Comment by ninjaahhh** [comment]
@qizhou should we close the issue for now?

**Comment by qizhou** [comment]
Basically, we want to make sure a node broadcasts a tx at most once.

If the queue may discard it,  it may have a race that:
1, both node 0 and 1 receives the tx
2, node 0 has full queue so the tx is discarded
3, node 1 adds the tx to queue and broadcast it
4, node 0 receives the tx and the queue is not full now.  node 0 broadcasts it again
5, node 1 discards the tx in the queue because the queue is again.
6, node 1 receives the tx and the queue is not full now.  node 1 broadcasts it again.
And this may repeat forever.

Admittedly that this is a very rare case, but I just highlight a possibility.  Let us watch the network and close it at the moment.
